# Gaussian Elimination

## Standard Gaussian Elimination

In [ ]:

# Gaussian Elimination Without Pivoting

import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)

    # Forward Elimination
    for k in range(n - 1):
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x


### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination(A1, b1)
print("A:", A1)
print("\nB:", b1)
print("\nSolution:", x1)


A: [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

B: [1 3 6]

Solution: [0.2 0.1 0.3]


### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


## Gaussian Elimination with Partial Pivoting

In [ ]:

# Gaussian Elimination with Partial Pivoting

import numpy as np

def gaussian_elimination_partial_pivoting(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)

    for k in range(n - 1):
        # Partial Pivoting
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]

        # Elimination
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination_partial_pivoting(A1, b1)

print("A =\n", A1)
print("\nb =", b1)
print("\nSolution x =", x1)
print()


A =
 [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

b = [1 3 6]

Solution x = [0.2 0.1 0.3]



### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination_partial_pivoting(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination_partial_pivoting(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


## Gaussian Elimination with Complete Pivoting

In [ ]:

# Gaussian Elimination with Complete Pivoting

import numpy as np

def gaussian_elimination_complete_pivoting(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)
    P = np.arange(n)

    for k in range(n - 1):
        # Complete Pivoting
        sub_matrix = np.abs(A[k:, k:])
        i_max, j_max = np.unravel_index(np.argmax(sub_matrix, axis=None), sub_matrix.shape)
        i_max += k
        j_max += k

        if i_max != k:
            A[[k, i_max]] = A[[i_max, k]]
            b[[k, i_max]] = b[[i_max, k]]
        if j_max != k:
            A[:, [k, j_max]] = A[:, [j_max, k]]
            P[[k, j_max]] = P[[j_max, k]]

        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    # Reorder x according to original column order
    x_ordered = np.zeros(n)
    for i in range(n):
        x_ordered[P[i]] = x[i]
    return x_ordered


### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination_complete_pivoting(A1, b1)
print("A:", A1)
print("\nB:", b1)
print("\nSolution:", x1)


A: [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

B: [1 3 6]

Solution: [0.2 0.1 0.3]


### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination_complete_pivoting(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination_complete_pivoting(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]
