## Standard Gaussian Elimination

In [ ]:

# Gaussian Elimination Without Pivoting

import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)

    # Forward Elimination
    for k in range(n - 1):
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x


### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination(A1, b1)
print("A:", A1)
print("\nB:", b1)
print("\nSolution:", x1)


A: [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

B: [1 3 6]

Solution: [0.2 0.1 0.3]


### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


## Gaussian Elimination with Partial Pivoting

In [ ]:

# Gaussian Elimination with Partial Pivoting

import numpy as np

def gaussian_elimination_partial_pivoting(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)

    for k in range(n - 1):
        # Partial Pivoting
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]

        # Elimination
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination_partial_pivoting(A1, b1)

print("A =\n", A1)
print("\nb =", b1)
print("\nSolution x =", x1)
print()


A =
 [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

b = [1 3 6]

Solution x = [0.2 0.1 0.3]



### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination_partial_pivoting(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination_partial_pivoting(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


## Gaussian Elimination with Complete Pivoting

In [ ]:

# Gaussian Elimination with Complete Pivoting

import numpy as np

def gaussian_elimination_complete_pivoting(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)
    P = np.arange(n)

    for k in range(n - 1):
        # Complete Pivoting
        sub_matrix = np.abs(A[k:, k:])
        i_max, j_max = np.unravel_index(np.argmax(sub_matrix, axis=None), sub_matrix.shape)
        i_max += k
        j_max += k

        if i_max != k:
            A[[k, i_max]] = A[[i_max, k]]
            b[[k, i_max]] = b[[i_max, k]]
        if j_max != k:
            A[:, [k, j_max]] = A[:, [j_max, k]]
            P[[k, j_max]] = P[[j_max, k]]

        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    # Reorder x according to original column order
    x_ordered = np.zeros(n)
    for i in range(n):
        x_ordered[P[i]] = x[i]
    return x_ordered


### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination_complete_pivoting(A1, b1)
print("A:", A1)
print("\nB:", b1)
print("\nSolution:", x1)


A: [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

B: [1 3 6]

Solution: [0.2 0.1 0.3]


### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination_complete_pivoting(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination_complete_pivoting(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


## Scaled Partial Pivoting

In [ ]:

# Gaussian Elimination with Scaled Partial Pivoting

import numpy as np

def gaussian_elimination_scaled_partial_pivoting(A, b):
    n = len(b)
    A = A.astype(float)
    b = b.astype(float)

    scale = np.max(np.abs(A), axis=1)
    for k in range(n - 1):
        # Scaled Partial Pivoting
        ratios = np.abs(A[k:, k]) / scale[k:]
        max_row = np.argmax(ratios) + k
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]
            scale[[k, max_row]] = scale[[max_row, k]]

        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

### Example 1

In [ ]:
A1 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 18, 10]])
b1 = np.array([1, 3, 6])
x1 = gaussian_elimination_scaled_partial_pivoting(A1, b1)
print("A:", A1)
print("\nB:", b1)
print("\nSolution:", x1)


A: [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 10]]

B: [1 3 6]

Solution: [0.2 0.1 0.3]


### Example 2

In [ ]:
A2 = np.array([[10, 2, -1],
               [-3, -6, 2],
               [1, 1, 5]])
b2 = np.array([27, -61.5, -21.5])
x2 = gaussian_elimination_scaled_partial_pivoting(A2, b2)
print("A:", A2)
print("\nB:", b2)
print("\nSolution:", x2)


A: [[10  2 -1]
 [-3 -6  2]
 [ 1  1  5]]

B: [ 27.  -61.5 -21.5]

Solution: [ 0.5  8.  -6. ]


### Example 3

In [ ]:
A3 = np.array([[1, 1, 1],
               [0, 2, 5],
               [0, 0, 3]])
b3 = np.array([6, -4, 3])
x3 = gaussian_elimination_scaled_partial_pivoting(A3, b3)
print("A:", A3)
print("\nB:", b3)
print("\nSolution:", x3)


A: [[1 1 1]
 [0 2 5]
 [0 0 3]]

B: [ 6 -4  3]

Solution: [ 9.5 -4.5  1. ]


# Factorisation

## LU Decomposition

In [ ]:
def lu_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]
    U = [[0.0] * n for _ in range(n)]

    for i in range(n):
        for k in range(i, n):
            sum_ = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - sum_

        for k in range(i, n):
            if i == k:
                L[i][i] = 1.0
            else:
                sum_ = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (A[k][i] - sum_) / U[i][i]

    return L, U

def print_matrix(M, name):
    print(f"{name}:")
    for row in M:
        print(["{0:8.2f}".format(val) for val in row])
    print()


### Example 1

In [ ]:
A1 = [
    [2, -1, -2],
    [-4, 6, 3],
    [-4, -2, 8]
]
L1, U1 = lu_decomposition(A1)
print_matrix(L1, "L1")
print_matrix(U1, "U1")


L1:
['    1.00', '    0.00', '    0.00']
['   -2.00', '    1.00', '    0.00']
['   -2.00', '   -1.00', '    1.00']

U1:
['    2.00', '   -1.00', '   -2.00']
['    0.00', '    4.00', '   -1.00']
['    0.00', '    0.00', '    3.00']



### Example 2

In [ ]:
A2 = [
    [10, -1, 2],
    [-1, 11, -1],
    [2, -1, 10]
]

L2, U2 = lu_decomposition(A2)
print_matrix(L2, "L2")
print_matrix(U2, "U2")


L2:
['    1.00', '    0.00', '    0.00']
['   -0.10', '    1.00', '    0.00']
['    0.20', '   -0.07', '    1.00']

U2:
['   10.00', '   -1.00', '    2.00']
['    0.00', '   10.90', '   -0.80']
['    0.00', '    0.00', '    9.54']



### Example 3

In [ ]:
A3 = [
    [1, 1/2, 1/3],
    [1/2, 1/3, 1/4],
    [1/3, 1/4, 1/5]
]
L3, U3 = lu_decomposition(A3)
print_matrix(L3, "L3")
print_matrix(U3, "U3")

L3:
['    1.00', '    0.00', '    0.00']
['    0.50', '    1.00', '    0.00']
['    0.33', '    1.00', '    1.00']

U3:
['    1.00', '    0.50', '    0.33']
['    0.00', '    0.08', '    0.08']
['    0.00', '    0.00', '    0.01']



## DoLittle

In [ ]:
def doolittle_lu_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]
    U = [[0.0] * n for _ in range(n)]

    for i in range(n):
        # Set diagonal of L to 1
        L[i][i] = 1.0

        # Compute U row
        for j in range(i, n):
            U[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(i))

        # Compute L column
        for j in range(i+1, n):
            if U[i][i] == 0:
                raise ZeroDivisionError("Division by zero during LU decomposition")
            L[j][i] = (A[j][i] - sum(L[j][k] * U[k][i] for k in range(i))) / U[i][i]

    return L, U


### Example 1

In [ ]:
A1 = [
    [2, -1, -2],
    [-4, 6, 3],
    [-4, -2, 8]
]
L1, U1 = doolittle_lu_decomposition(A1)
print_matrix(L1, "L1")
print_matrix(U1, "U1")

L1:
['    1.00', '    0.00', '    0.00']
['   -2.00', '    1.00', '    0.00']
['   -2.00', '   -1.00', '    1.00']

U1:
['    2.00', '   -1.00', '   -2.00']
['    0.00', '    4.00', '   -1.00']
['    0.00', '    0.00', '    3.00']



### Example 2

In [ ]:
A2 = [
    [10, -1, 2],
    [-1, 11, -1],
    [2, -1, 10]
]

L2, U2 = doolittle_lu_decomposition(A2)
print_matrix(L2, "L2")
print_matrix(U2, "U2")


L2:
['    1.00', '    0.00', '    0.00']
['   -0.10', '    1.00', '    0.00']
['    0.20', '   -0.07', '    1.00']

U2:
['   10.00', '   -1.00', '    2.00']
['    0.00', '   10.90', '   -0.80']
['    0.00', '    0.00', '    9.54']



### Example 3

In [ ]:
A3 = [
    [1, 1/2, 1/3],
    [1/2, 1/3, 1/4],
    [1/3, 1/4, 1/5]
]
L3, U3 = doolittle_lu_decomposition(A3)
print_matrix(L3, "L3")
print_matrix(U3, "U3")

L3:
['    1.00', '    0.00', '    0.00']
['    0.50', '    1.00', '    0.00']
['    0.33', '    1.00', '    1.00']

U3:
['    1.00', '    0.50', '    0.33']
['    0.00', '    0.08', '    0.08']
['    0.00', '    0.00', '    0.01']



## Crout's Method

In [ ]:
def crout_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]
    U = [[0.0] * n for _ in range(n)]

    for j in range(n):
        U[j][j] = 1.0  # Diagonal of U is 1

        for i in range(j, n):
            L[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(j))

        for i in range(j+1, n):
            if L[j][j] == 0:
                raise ZeroDivisionError("Zero pivot encountered")
            U[i][j] = (A[j][i] - sum(L[j][k] * U[k][i] for k in range(j))) / L[j][j]

    return L, U


### Example 1

In [ ]:
A1 = [
    [2, -1, -2],
    [-4, 6, 3],
    [-4, -2, 8]
]
L1, U1 = crout_decomposition(A1)
print_matrix(L1, "L1")
print_matrix(U1, "U1")

L1:
['    2.00', '    0.00', '    0.00']
['   -4.00', '    6.00', '    0.00']
['   -4.00', '   -2.00', '    8.00']

U1:
['    1.00', '    0.00', '    0.00']
['   -0.50', '    1.00', '    0.00']
['   -1.00', '    0.50', '    1.00']



### Example 2

In [ ]:
A2 = [
    [10, -1, 2],
    [-1, 11, -1],
    [2, -1, 10]
]

L2, U2 = crout_decomposition(A2)
print_matrix(L2, "L2")
print_matrix(U2, "U2")


L2:
['   10.00', '    0.00', '    0.00']
['   -1.00', '   11.00', '    0.00']
['    2.00', '   -1.00', '   10.00']

U2:
['    1.00', '    0.00', '    0.00']
['   -0.10', '    1.00', '    0.00']
['    0.20', '   -0.09', '    1.00']



### Example 3

In [ ]:
A3 = [
    [1, 1/2, 1/3],
    [1/2, 1/3, 1/4],
    [1/3, 1/4, 1/5]
]
L3, U3 = crout_decomposition(A3)
print_matrix(L3, "L3")
print_matrix(U3, "U3")

L3:
['    1.00', '    0.00', '    0.00']
['    0.50', '    0.33', '    0.00']
['    0.33', '    0.25', '    0.20']

U3:
['    1.00', '    0.00', '    0.00']
['    0.50', '    1.00', '    0.00']
['    0.33', '    0.75', '    1.00']



## Cholesky

In [ ]:
import math

def cholesky_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]

    for i in range(n):
        for j in range(i + 1):
            sum_k = sum(L[i][k] * L[j][k] for k in range(j))

            if i == j:
                val = A[i][i] - sum_k
                if val <= 0:
                    raise ValueError("Matrix is not positive-definite")
                L[i][j] = math.sqrt(val)
            else:
                L[i][j] = (A[i][j] - sum_k) / L[j][j]

    return L


### Example 1

In [ ]:
A1 = [
    [25, 15, -5],
    [15, 18,  0],
    [-5,  0, 11]
]

L1 = cholesky_decomposition(A1)
print_matrix(L1, "L1")

L1:
['    5.00', '    0.00', '    0.00']
['    3.00', '    3.00', '    0.00']
['   -1.00', '    1.00', '    3.00']



### Example 2

In [ ]:
A2 = [
    [6, 15, 55],
    [15, 55, 225],
    [55, 225, 979]
]

L2 = cholesky_decomposition(A2)
print_matrix(L2, "L2")


L2:
['    2.45', '    0.00', '    0.00']
['    6.12', '    4.18', '    0.00']
['   22.45', '   20.92', '    6.11']



### Example 3

In [ ]:
A3 = [
    [1, 1/2, 1/3],
    [1/2, 1/3, 1/4],
    [1/3, 1/4, 1/5]
]
L3 = cholesky_decomposition(A3)
print_matrix(L3, "L3")

L3:
['    1.00', '    0.00', '    0.00']
['    0.50', '    0.29', '    0.00']
['    0.33', '    0.29', '    0.07']

